apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job2
spec:
  template:
    metadata:
      name: dbInitJob2
    spec:
      restartPolicy: Never
      containers:
        - name: "post-install-job"
          image: postgres:11.7
          env:
            - name: POSTGRES_PASSWORD
              value: "passwd"
          command:
            - sh
            - "-c"
            - |
              sleep 30 && {{ printf "psql postgres://%s:%s@%s/%s" .Values.externalPostgresql.postgresqlUsername .Values.externalPostgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.externalPostgresql.postgresqlDatabase }} <<'EOF'
                CREATE SEQUENCE user_seq minvalue 1;

                CREATE TABLE system_user
                (
                    id          bigint       NOT NULL,
                    username    varchar(255) NOT NULL,
                    first_name  varchar(255) NULL,
                    last_name   varchar(255) NOT NULL,
                    email       varchar(255) NOT NULL,
                    phone       varchar(50)  NULL,
                    create_date timestamp    NOT NULL,
                    update_date timestamp    NOT NULL,
                    CONSTRAINT user_id_pk PRIMARY KEY (id)
                );

              EOF
  backoffLimit: 0
