{
 "title": "Arch task",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": " latency по методам квантиль 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "RPS by API methods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count_total[1m])) ",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": " latency по методам квантиль 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "# of 5xx errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status,exported_endpoint) (rate(app_request_count_total{http_status=~\"5.+\"}[1m]))",
     "legendFormat": "{{ http_status }} by endpoint {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": " latency по методам квантиль 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": " latency по методам квантиль max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "quantile 1"
    }
   ]
  }
 ]
}