apiVersion: v1
kind: Pod
metadata:
  name: hello-demo
  labels:
    app: hello-demo
spec:
  containers:
    - name: hello-demo
      image: docker-spring:0.3.0
      ports:
        - containerPort: 80
